line_length: 200

type_name:
  max_length: 100

type_body_length: 400

identifier_name:
  min_length: 1
  max_length: 100
  excluded:
    - i
    - id

function_body_length: 100

file_length:
    warning: 1000
    error: 1500
    ignore_comment_only_lines: true

opt_in_rules:
  - force_unwrapping

type_name:
  validates_start_lowercase: false
  allowed_symbols: "_"

cyclomatic_complexity:
  ignores_case_statements: true

identifier_name:
  allowed_symbols: "_"
  validates_start_lowercase: true
  min_length: 2
  max_length: 
    warning: 90
    error: 100
  excluded:
    - id

large_tuple:
  warning: 3
  error: 4

disabled_rules: # rule identifiers to exclude from running
  - comma
  - trailing_whitespace

excluded: # paths to ignore during linting. Takes precedence over `included`.
  - Pods
  - Carthage
